name: Build Docker Image s6-rc with buildx

on:
  # Allow manual dispatch
  workflow_dispatch:

# Cancel previous runs when a new one is triggered
concurrency:
  group: docker-build-s6-rc
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code to main branch
        uses: actions/checkout@v4

      - name: Setup Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: npm

      - name: Verify Node.js version
        run: node -v

      - name: Verify Npm version
        run: npm -v

      - name: Set metadata
        id: meta
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "VCS_REF=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - name: Write build metadata to .dockerbuild.json
        run: |
          cat > .dockerbuild.json <<EOF
          {
            "sha": "${GITHUB_SHA}",
            "sha7": "${GITHUB_SHA::7}",
            "event": "${GITHUB_EVENT_NAME}",
            "workflow": "${GITHUB_WORKFLOW}",
            "type": "${GITHUB_REF_TYPE}",
            "name": "${GITHUB_REF_NAME}",
            "dev": false
          }
          EOF

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Run Docker Buildx with Dockerfile.s6-rc for version ${{ steps.meta.outputs.VERSION }}
        run: |
          docker buildx build \
            --no-cache \
            --pull \
            --platform linux/amd64,linux/arm64 \
            -f docker/Dockerfile.s6-rc \
            -t luligu/matterbridge:s6-rc \
            -t luligu/matterbridge:s6-rc-${{ steps.meta.outputs.VERSION }} \
            -t luligu/matterbridge:2026.2.5 \
            --build-arg VERSION=${{ steps.meta.outputs.VERSION }} \
            --build-arg VCS_REF=${{ steps.meta.outputs.VCS_REF }} \
            --build-arg BUILD_DATE=${{ steps.meta.outputs.BUILD_DATE }} \
            --push .
          docker manifest inspect luligu/matterbridge:s6-rc
